services:
  nginx:
    container_name: chirrio_nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/app/webapp/static
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - web
    restart: "on-failure"
    networks:
      - server_net
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
  web:
    container_name: chirrio_server
    volumes:
      - .:/chirrio_server
      - static_volume:/home/app/webapp/static
    depends_on:
      - db
    build: .
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py initadmin &&
      daphne -b 0.0.0.0 -p 8000 chirrio_server.asgi:application"
    image: chirrio_image
    expose:
      - 8000
    networks:
      - server_net
    environment:
      - APP_HOST=${APP_HOST}

  db:
    container_name: chirrio_db
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - ${DB_PORT}
    networks:
      - server_net

volumes:
  pgdata:
  static_volume:
  redis:

networks:
  server_net: