# Generated by Django 4.2.4 on 2023-10-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="chatroom_uid",
            field=models.CharField(
                default="6612278e-3c12-4023-92d3-3a019b6a8f15", max_length=36
            ),
        ),
        migrations.AlterField(
            model_name="chirriouser",
            name="useruid",
            field=models.CharField(
                default="fb701a65-d3fd-4028-88dc-ff8d7f2316af", max_length=36
            ),
        ),
    ]
