# Generated by Django 4.2.4 on 2023-09-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatroom_alter_chirriouser_useruid_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chirriouser",
            name="role",
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="chatroom_uid",
            field=models.CharField(
                default="eaa1587a-ac45-48fc-87a8-ab6a46cc0964", max_length=36
            ),
        ),
        migrations.AlterField(
            model_name="chirriouser",
            name="useruid",
            field=models.CharField(
                default="1a26aaee-a218-4a6e-a3fa-638eb9e97f49", max_length=36
            ),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
