# Generated by Django 4.2.4 on 2023-09-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_chirriouser_role_alter_chatroom_chatroom_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="chatroom_uid",
            field=models.CharField(
                default="ca87ce82-d35a-4887-92aa-e5d5207ed7fa", max_length=36
            ),
        ),
        migrations.AlterField(
            model_name="chirriouser",
            name="useruid",
            field=models.CharField(
                default="d6354c94-3cb1-4f61-a4b9-fc9953475614", max_length=36
            ),
        ),
    ]
