# Generated by Django 4.2.4 on 2023-10-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_chatroom_number_of_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chirriouser",
            name="image",
            field=models.ImageField(default="user.png", upload_to=""),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="chatroom_uid",
            field=models.CharField(
                default="2297741c-26b6-48a2-afc5-47c50e9aa79c", max_length=36
            ),
        ),
        migrations.AlterField(
            model_name="chirriouser",
            name="useruid",
            field=models.CharField(
                default="4420a876-fd0b-4e56-886d-fe02a2e249c2", max_length=36
            ),
        ),
    ]
