# Generated by Django 4.2.4 on 2023-10-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_chatroom_number_of_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chirriouser",
            name="image",
            field=models.ImageField(default="user.png", upload_to=""),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="chatroom_uid",
            field=models.CharField(
                default="a915a1a8-beb9-4da9-b664-f8faad421dab", max_length=36
            ),
        ),
        migrations.AlterField(
            model_name="chirriouser",
            name="useruid",
            field=models.CharField(
                default="4fef95d3-aa24-4c1c-a6d0-0673efe2b563", max_length=36
            ),
        ),
    ]
