# Generated by Django 4.2.4 on 2023-10-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_chirriouser_image_alter_chatroom_chatroom_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="chatroom_uid",
            field=models.CharField(
                default="6f614602-9a8c-4d4c-989b-52b7f8a9b30c", max_length=36
            ),
        ),
        migrations.AlterField(
            model_name="chirriouser",
            name="useruid",
            field=models.CharField(
                default="68ba768f-09c6-487d-a0a5-8b4d9631f7e4", max_length=36
            ),
        ),
    ]
