services:
  web:
    container_name: chirrio_server

  db:
    container_name: chirrio_db
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    container_name: chirrio_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: